openapi: '3.0.0'
info:
  version: 0.0-oas3
  title: prediction/info - Hayden Moore
  description: >-
    service to get a prediction for likelihood of heartfailure using swagger-3.0.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /prediction/{id}:
    get:
      tags:
        - PREDICTION
      operationId: functions.my_prediction
      description: 'takes array of 12 components, returns heart failure prediction'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'heart failure risk prediction'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PREDICTION'
  /info:
    get:
      tags:
        - INFO
      operationId: functions.info
      description: 'returns information about healthy levels for features'
      responses:
        '200':
          description: 'heart failure features info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/INFO'
  /test:
    get:
      tags:
        - TEST
      operationId: functions.prediction_test
      description: 'returns the metrics for the trained model'
      #produces:
        #- "application/json"
      responses:
        '200':
          description: 'heart failure model metrics'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TEST'
  /score:
    get:
      tags:
        - SCORE
      operationId: functions.model_score
      description: 'returns the metrics for the trained model'
      #produces:
        #- "application/json"
      responses:
        '200':
          description: 'heart failure model metrics'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCORE'

servers:
  - url: 'http://localhost:8080/'
components:
  schemas:
    PREDICTION:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    SCORE:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    TEST:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    INFO:
      type: object
      required:
        - model
      properties:
        model:
          type: string