swagger: '3.0.0'
info:
  version: 0.0-oas3
  title: prediction/info - Hayden Moore
  description: >-
    service to get a prediction for likelihood of heartfailure using swagger-3.0.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /prediction/{id}:
    get:
      tags:
        - PREDICTION
      operationId: ml_project.my_prediction
      description: 'takes array of 8 components, returns heart failure prediction'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'heart failure risk prediction'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PREDICTION'
  /score:
    get:
      tags:
        - SCORE
      operationId: ml_project.my_score
      description: 'returns the metrics for the trained model'
      produces:
        - "application/json"
      responses:
        '200':
          description: 'heart failure model metrics'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCORE'
  /roc:
    get:
      tags:
        - ROC
      operationId: ml_project.my_roc
      description: 'shows receiver operating characteristic for model'
      produces:
        - "application/json"
      responses:
        '200':
          description: 'roc graph'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ROC'
servers:
  - url: 'http://localhost:8080/engr-222'
components:
  schemas:
    PREDICTION:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    SCORE:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    ROC:
      type: object
      required:
        - model
      properties:
        model:
          type: string